### ISSUE TITLE
The wallet does not offer to sign anything when calling AuthClient.request()

### ISSUE THREAD

**Issue by gHashTag** [WalletConnect/auth-client-js#56]
Why is nothing happening (there is no event and a transaction that needs to be signed)? I've reviewed  a lot of the project's source code and didn't really understand what was wrong

Code:

![image](https://user-images.githubusercontent.com/6774813/211786756-8e8cbec8-a7cc-44d3-93eb-f672e782fb52.jpeg)

Behavior:

https://user-images.githubusercontent.com/6774813/211786655-7364596e-2e2b-4185-a465-f10f04af36e8.MOV

Development environment:
"react-native": "0.70.6"
"@walletconnect/auth-client": "^2.0.2"
@walletconnect/react-native-compat": "^2.2.1"

**Comment by gHashTag** [comment]
Same in https://react-app.walletconnect.com

https://user-images.githubusercontent.com/6774813/211826388-57f19e84-aa62-4207-9dd3-139263379c0b.MOV

**Comment by ganchoradkov** [comment]
hey @gHashTag Metamask is not yet supporting v2, that is why you can't connect.
Please try with one of the wallets in this list that do support it https://explorer.walletconnect.com/?type=wallet&version=2
