### ISSUE TITLE
How to call another application (other than metamask) for authentication?

### ISSUE THREAD

**Issue by gHashTag** [WalletConnect/auth-client-js#57]
After looking at the source code, I did not find the answer to this question

According to the documentation, I did not understand how to do this

I tried to substitute different parameters into the function and it didn't work out either

**Comment by ganchoradkov** [comment]
Hey @gHashTag, you don't have to directly call an application but rather scan the app's QR code with a wallet supporting Auth

**Comment by gHashTag** [comment]
This is how I make a mobile app 😅
