### ISSUE TITLE
Auth Client Sends Two Requests for Known Pairing

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/auth-client-js#60]
https://github.com/WalletConnect/auth-client-js/blob/main/packages/auth-client/src/controllers/engine.ts

The current implementation `request` function will send two requests if the provided topic is a known pairing.

Is this intentional? 
It feels redundant.

**Comment by bkrem** [comment]
You're correct it's doing unnecessary work atm in the known pairing flow and not returning early as it should. Thanks for pointing this out 🙏 

Hoping to have a fix out tomorrow addressing this + simplified pairing creation.
