### ISSUE TITLE
Auth Client Request's Pairing API Usage is Different From Sign Client

### ISSUE THREAD

**Issue by Luzzotica** [WalletConnect/auth-client-js#61]
The Sign Client calls the `pairing.create()` function to create the pairing correctly with the expiration and proper subscriptions.

The Auth Client doesn't do this, and appears to attempt to create a pairing manually if a pairingTopic isn't provided.

Is this intentional?
I feel like if you would like to use the Auth API without the Sign API, it would be riddled with bugs due to this fact.

It's likely that not many people use JUST the Auth API though, so it hasn't been a prevalent issue.

**Comment by bkrem** [comment]
Hi @Luzzotica,

> The Auth Client doesn't do this, and appears to attempt to create a pairing manually if a pairingTopic isn't provided.

Yes the AuthClient does currently still do the steps manually that `pairing.create()` does under the hood. This is a symptom of the Pairing API only coming into existence after this iteration of AuthClient had been written.

Either way this is something that needs to be aligned/abstracted via calling `pairing.create()`, so thank you for raising this.

> I feel like if you would like to use the Auth API without the Sign API, it would be riddled with bugs due to this fact.

Could you explain why here? The behaviour (setting expiry, subscribing to pairing topic) should still match at the end of the day as far as I can tell.
