### ISSUE TITLE
[Feat] Integrate AuthClient with VerifyAPI into react-auth-dapp

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/auth-client-js#74]
## Context

- Our [sample auth dapp](https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-auth) provides a testing ground for wallets integrating Auth.
- Once Verify API is part of the AuthClient, we should ensure it's exposed and configured properly to help the entire web3wallet team dogfood their implementations of Verify API.

## Dependencies

- Depends on:
	- #72 
	- Publishing updated version of `@walletconnect/auth-client` containing the Verify API changes

**Comment by JonathanConn** [comment]
Need to publish updated `@walletconnect/auth-client` and will be ready for PR

**Comment by JonathanConn** [comment]
Published auth client canary, ran into issue where the verify server is blocking our domain. Gancho is handling this



![Image](https://user-images.githubusercontent.com/37967804/236342476-2d437886-e21f-4306-9f5e-e4a5dd546e53.png)

**Comment by JonathanConn** [comment]
Waiting for new auth package to be published tonight to update then merge
